#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : os-api-ref
Version  : 2.0.0
Release  : 15
URL      : https://files.pythonhosted.org/packages/cb/46/c64d106664269cd344fcb23ef42eaf0c3f9b1b16ad870e587a5e054db742/os-api-ref-2.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/cb/46/c64d106664269cd344fcb23ef42eaf0c3f9b1b16ad870e587a5e054db742/os-api-ref-2.0.0.tar.gz
Summary  : Sphinx Extensions to support API reference sites in OpenStack
Group    : Development/Tools
License  : Apache-2.0
Requires: os-api-ref-license = %{version}-%{release}
Requires: os-api-ref-python = %{version}-%{release}
Requires: os-api-ref-python3 = %{version}-%{release}
Requires: PyYAML
Requires: Sphinx
Requires: openstackdocstheme
Requires: pbr
Requires: six
BuildRequires : PyYAML
BuildRequires : Sphinx
BuildRequires : buildreq-distutils3
BuildRequires : openstackdocstheme
BuildRequires : pbr
BuildRequires : six

%description
========================
Team and repository tags
========================

.. image:: https://governance.openstack.org/tc/badges/os-api-ref.svg
    :target: https://governance.openstack.org/tc/reference/tags/index.html

.. Change things from this point on

os-api-ref
==========

Sphinx Extensions to support API reference sites in OpenStack

This project is a collection of sphinx stanzas that assist in building
an API Reference site for an OpenStack project in RST. RST is great
for unstructured English, but displaying semi structured (and
repetitive) data in tables is not its strength. This provides tooling
to insert semi-structured data describing request and response
parameters and status or error messages, and turn those into nice tables.

The project also includes a set of styling (and javascript) that is
expected to layer on top of a Sphinx theme base. This addition
provides a nice set of collapsing sections for REST methods and
javascript controls to expand / collapse all sections.

Features
--------

* Sphinx stanza ``rest_method`` describing the method and resource for a REST
  API call. Lets authors write simply and also gives readers a clean way to
  scan all methods then click a button to get more information about a method.
* Sphinx stanza ``rest_parameters`` used to insert semi-structured data into
  the RST files describing the parameters users can send with the request. The
  stanza points to a structured YAML file, ``parameters.yaml``.
* Sphinx stanza ``rest_status_code`` used to insert pointers to error or status
  codes returned by the service. Points to a structured YAML file,
  ``http_codes.yaml``.

TODO
----

A list, in no particular order, of things we should do in this
project. If you would like to contribute to any of these please show
up in ``#openstack-dev`` on IRC and ask for ``sdague`` or ``mugsie``
to discuss or send an email to the openstack-discuss@lists.openstack.org list
with [api] in the subject line.

* Enhance documentation with more examples and best practices
* Testing for the code
* ``max_microversion`` parameter support - so that we automatically
  tag parameters that have been removed
* Make a microversion selector, so that you can get a version of the api-ref
  that hides all microversion elements beyond your selected version
  (this one is going to be a bit of complex javascript), in progress.

Potential ideas
~~~~~~~~~~~~~~~

These aren't even quite todos, but just ideas about things that might
be useful.

* ``.. literalinclude`` is good for API samples files to be included,
  but should we have more markup that includes the full ``REST /URL``
  as well.


Sphinx stanzas
--------------

**rest_method**: Enter the REST method, such as GET, PUT, POST, DELETE,
followed by the resource (not including an endpoint) for the call. For
example::

    .. rest_method:: PUT /v2/images/{image_id}/file

**rest_parameters**: Enter a reference to a ``parameters.yaml`` file and
indicate which parameter you want to document. For example::

    .. rest_parameters:: images-parameters.yaml

       - Content-type: Content-Type-data
       - image_id: image_id-in-path

Where the ``images-parameters.yaml`` file contains pointers named
``Content-type`` and ``image_id`` and descriptions for each.

**rest_status_code**: Enter a reference to a ``http-status.yaml`` file and
indicate which errors or status codes you want to document. You can also add
a pointer to more precise descriptions for each code. For example::

    .. rest_status_code:: success http-codes.yaml

      - 204

    .. rest_status_code:: error http-codes.yaml

      - 400: informal
      - 401
      - 403
      - 404
      - 409
      - 410: image-data-410
      - 413: image-data-413
      - 415: image-data-415
      - 500: informal
      - 503: image-data-503


* Free software: Apache license
* Documentation: https://docs.openstack.org/os-api-ref/latest/
* Source: https://opendev.org/openstack/os-api-ref

%package license
Summary: license components for the os-api-ref package.
Group: Default

%description license
license components for the os-api-ref package.


%package python
Summary: python components for the os-api-ref package.
Group: Default
Requires: os-api-ref-python3 = %{version}-%{release}

%description python
python components for the os-api-ref package.


%package python3
Summary: python3 components for the os-api-ref package.
Group: Default
Requires: python3-core
Provides: pypi(os-api-ref)

%description python3
python3 components for the os-api-ref package.


%prep
%setup -q -n os-api-ref-2.0.0
cd %{_builddir}/os-api-ref-2.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583193252
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os-api-ref
cp %{_builddir}/os-api-ref-2.0.0/LICENSE %{buildroot}/usr/share/package-licenses/os-api-ref/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os-api-ref/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
